### ISSUE TITLE
Additional documentation

### ISSUE THREAD

**Issue by pierreburgy** [mrauter/strapi-generate-docs#1]
Instead of adding the specific documentation inside a new file (`swagger.json`), what do you think about adding a new key `docs` / `doc` / `documentation` inside each route in the `routes.json` file?

Example for user module:

```
{
  "routes": {
    "GET /user": {
      "controller": "User",
      "action": "find",
      "policies": [
        "isAuthorized"
      ],
      "documentation": {
        "summary": "Get auth token",
        "parameters": [
          {
            "name": "identifier",
            "in": "formData",
            "required": true,
            "type": "string"
          },
          {
            "name": "password",
            "in": "formData",
            "required": true,
            "type": "string"
          }
        ],
        "security": []
      }
    },
    ...
  }
}
```

**Comment by mrauter** [comment]
yes i also think that would be a better solution.. first i wanted to seperate strapi and docs module config, but i think most people want to use a documentation module so it makes sense to add this directly in the routes config.
